var bannaPrice = 10;
console.log(typeof bannaPrice);
var temp =30;
console.log(temp);
var age_diff= "jakir";
console.log(age_diff);
console.log(typeof age_diff);
var isHot= true;
console.log(isHot);
console.log(typeof isHot);
var promise = "I am A boy wanna marry a girl";
console.log(promise.toLocaleLowerCase());
console.log(promise.indexOf('am'));
console.log(promise.split('a'));
var number1=25;
var number2=15.5;
console.log(number1+number2);
var number1='25';
var number2=15.5;
console.log(number1+number2);
var number1=25;
var number2='15.5';
number2=+number2;
console.log(number1+number2);
var number1=25;
var number2='15.5';
number1=''+number1;
console.log(typeof number1);
var number1=25;
var number2='15.5';
number2=parseFloat(number2);
console.log(number1+number2);
var number1=25;
var number2='15.5';
number2=parseInt(number2);
console.log(number1+number2);
var number1=0.3;
var number2=0.2;
number1++;
var total=number1%number2; //any mathemetical operation
console.log(total.toFixed(5));
var number1 = -5;
var absoluteValue = Math.abs(number1);
console.log(absoluteValue);
var number1 = 5.49;
//var number1 = 5.5;
//var number1 = 5.5454;
var roundValue = Math.round(number1);
console.log(roundValue);
var number1 = 5.49;
var roundValue = Math.ceil(number1);
console.log(roundValue);
var number1 = 5.49;
var roundValue = Math.floor(number1);
console.log(roundValue);
var number = Math.random()*100;
var randomValue = Math.round(number);
console.log(randomValue);
var date = new Date();                          //could be assigned
console.log(date);